title: The Cardboard Knight
email: your-email@example.com
author: me
subtitle: "The power of Board Game Geek, in your pocket"
description: >- # this means to ignore newlines until "baseurl:"
  A free, open-source app to drag BoardGameGeek into the modern age to support mobile devices.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
appstoreid : 123465
playstoreid : 123456

# Build settings
plugins:
  - jekyll-feed

collections:
  appfeatures:
      output: true
      permalink: /:collection/:name
  about:
      output: true
      permalink: /:collection/:name
  legal:
      output: true
      permalink: /:collection/:name

sociallinks:
  -
    title : "github"
    icon : "fa-github"
    url : "https://github.com/TheCardboardKnight/App"

sass:
    style: :compressed